import type { Metadata } from 'next'
import './globals.css'
import './dark.css'
import './dark-root-styles.css'
import Image from 'next/image'
import { headers } from 'next/headers'
import { ThemeProvider } from './context/theme'
import { Body } from './components/Body'
import { InternationalizationProvider } from './context/internationalization'
import { MobileNavButton } from './components/MobileNavButton'
import { Navbar } from './components/Navbar'
import { Footer } from './components/Footer'

export const metadata: Metadata = {
  title: 'Title | Business | Location, WA',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  const headersList = headers()
  const defaultLng = headersList.get('Accept-Language')

  return (
    <html lang="en">
      <InternationalizationProvider defaultLng={defaultLng}>
        <ThemeProvider>
          <Body>
            <header>
              {/* <!-- Mobile Nav Strip --> */}
              <div className="mobile-wrapper">
                <div className="mobile-nav container mobile-nav-container">
                  <Image
                    className="light"
                    id="mobile-logo"
                    src="/images/logo.svg"
                    alt="mobile_company_logo"
                    width="110"
                    height="32"
                  />
                  <Image
                    className="dark"
                    id="mobile-logo"
                    src="/images/logo-white.svg"
                    alt="mobile_company_logo"
                    width="110"
                    height="32"
                  />
                  {/* <!-- Hamburger Menu --> */}
                  <MobileNavButton />
                </div>
              </div>
              <Navbar />
            </header>

            {children}

            <Footer />
          </Body>
        </ThemeProvider>
      </InternationalizationProvider>
    </html>
  )
}
